#!/usr/bin/env bash

# update and install base packages
sudo apt-get update
sudo apt-get install rake git zsh -y

# install oh my zsh
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

# install janus
curl -Lo- https://bit.ly/janus-bootstrap | bash

# install dotfiles
git clone https://jakedahn@github.com/jakedahn/dotfiles.git
cp -r ./dotfiles/.* ~/
